services:
  db:
    image: postgres:14.4-alpine3.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
#      - pgdata:/var/lib/postgresql/data/pgdata
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./database/calories.csv:/calories.csv

volumes:
  pgdata:
